---
ID: "665678f9-fb80-4e57-a5a3-f27d25631255"
Parent: "110b6b12-d330-4a36-9f6e-8386a2e55f5a"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/User Defined/Base Templates/SelfServBase/Self Serv Base Configurations
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160513T151948Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
